### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by risacher** [kelly/node-i2c#47]
I repeatably get a segfault that I think is in i2c, but it takes a few hours for it to happen.  During that time, the process size grows slowly, so maybe it's a memory leak issue?

I am using node 0.10.33 and adafruit-i2c-lcd on a raspberry pi B; with i2c module pulled from latest github.  The test program scrolls text across the lcd display, changing the text on a 100ms interval.  

Unfortunately when the segfault happens, it seems to corrupt the stack, so I haven't been able to get a good backtrace in gdb or core file.

**Comment by arskb4ga** [comment]
Did this SEGV ever get resolved?

**Comment by risacher** [comment]
I don't think so.  I haven't tested it lately - that project went on indefinite hold.  I'll try it tonight.

**Comment by risacher** [comment]
I upgraded to node 0.12.6; ran npm update, which pulled in i2c v0.2.1.  I then ran my test program and let it run all night - no segfault.  I forgot to check for process growth.  I'm running the test again, but I think the problem is resolved.  If it hasn't crashed by tonight, I'll close the issue.

**Comment by arskb4ga** [comment]
Thanks for your work testing this! I am running Node 10.38 on a PI-2, I have not been able to get the PI to load version Node 12.  What platform are you running?  I tested with another i2c program and it ran OK, but I used readByte and not readyBytes (block), I would assume it would fail if I used the block mode also until upgrade node, based on my reading.

**Comment by risacher** [comment]
My pi's (I think I have 3) are RPi 1 Model B.  I installed node 0.12.6 via instructions at http://weworkweplay.com/play/raspberry-pi-nodejs/ - basically a installed a package built by heroku.

**Comment by arskb4ga** [comment]
Thanks, I will take a look at this, it will save me a lot of time if it works.

**Comment by arskb4ga** [comment]
I have been testing for a while with node 0.12.6 and it seems to be working fine.  I don't notice the memory leak that were there with 0.10.38. Strange it was intermittent when it came to how long the process ran before the segfault.

**Comment by risacher** [comment]
No crash; no leak.  Closing.
