### ISSUE TITLE
i2c simply doesn't work

### ISSUE THREAD

**Issue by steowens** [kelly/node-i2c#63]
So I have a simple class which emits a byte array to an i2c address.  When I run the node script it fails to interface with the device.  However when I run the same commands using i2cset on the command line, the setup works.  It is as though the i2c library is doing nothing at all.

**Comment by kelly** [comment]
What code are you using? Which version of node are you using? Which embedded system do you have?

**Comment by steowens** [comment]
I was using the code in this repo on a bealebone.  We ended up having to invoke I2c commands via the shell. to get things to work.
