### ISSUE TITLE
Install fails on BBB w/Debian

### ISSUE THREAD

**Issue by stormbytes** [kelly/node-i2c#66]
→ npm install i2c
-
> i2c@0.2.1 install /home/storm/node_modules/i2c
> node-gyp rebuild

make: Entering directory `/home/storm/node_modules/i2c/build'
  CXX(target) Release/obj.target/i2c/src/i2c.o
../src/i2c.cc: In function ‘void setAddress(int8_t)’:
../src/i2c.cc:22:14: error: ‘class v8::Isolate’ has no member named ‘ThrowException’
../src/i2c.cc:23:28: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
../src/i2c.cc: At global scope:
../src/i2c.cc:29:23: error: ‘FunctionCallbackInfo’ does not name a type
../src/i2c.cc:29:23: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/i2c.cc:29:43: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/i2c.cc: In function ‘void SetAddress(int)’:
../src/i2c.cc:31:28: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate*&)’
../src/i2c.cc:31:28: note: candidates are:
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const v8::HandleScope&’
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note: v8::HandleScope::HandleScope()
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
../src/i2c.cc:33:10: error: ‘args’ was not declared in this scope
../src/i2c.cc: At global scope:
../src/i2c.cc:37:17: error: ‘FunctionCallbackInfo’ does not name a type
../src/i2c.cc:37:17: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/i2c.cc:37:37: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/i2c.cc: In function ‘void Scan(int)’:
../src/i2c.cc:39:28: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate*&)’
../src/i2c.cc:39:28: note: candidates are:
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const v8::HandleScope&’
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note: v8::HandleScope::HandleScope()
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
../src/i2c.cc:42:52: error: ‘args’ was not declared in this scope
../src/i2c.cc:43:49: error: no matching function for call to ‘v8::Array::New(v8::Isolate*&, int)’
../src/i2c.cc:43:49: note: candidate is:
/usr/include/nodejs/deps/v8/include/v8.h:1758:32: note: static v8::Local<v8::Array> v8::Array::New(int)
/usr/include/nodejs/deps/v8/include/v8.h:1758:32: note:   candidate expects 1 argument, 2 provided
../src/i2c.cc:44:62: error: no matching function for call to ‘v8::Local<v8::Value>::New(v8::Isolate*&, v8::Handle<v8::Primitive>)’
../src/i2c.cc:44:62: note: candidate is:
/usr/include/nodejs/deps/v8/include/v8.h:4197:10: note: static v8::Local<T> v8::Local<T>::New(v8::Handle<T>) [with T = v8::Value]
/usr/include/nodejs/deps/v8/include/v8.h:4197:10: note:   candidate expects 1 argument, 2 provided
../src/i2c.cc:56:46: error: invalid conversion from ‘v8::Isolate*’ to ‘int32_t {aka int}’ [-fpermissive]
/usr/include/nodejs/deps/v8/include/v8.h:1392:34: error:   initializing argument 1 of ‘static v8::Local<v8::Integer> v8::Integer::New(int32_t, v8::Isolate*)’ [-fpermissive]
../src/i2c.cc:56:46: error: invalid conversion from ‘int’ to ‘v8::Isolate*’ [-fpermissive]
/usr/include/nodejs/deps/v8/include/v8.h:1392:34: error:   initializing argument 2 of ‘static v8::Local<v8::Integer> v8::Integer::New(int32_t, v8::Isolate*)’ [-fpermissive]
../src/i2c.cc:63:27: error: ‘class v8::Isolate’ has no member named ‘GetCurrentContext’
../src/i2c.cc: At global scope:
../src/i2c.cc:68:18: error: ‘FunctionCallbackInfo’ does not name a type
../src/i2c.cc:68:18: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/i2c.cc:68:38: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/i2c.cc: In function ‘void Close(int)’:
../src/i2c.cc:70:28: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate*&)’
../src/i2c.cc:70:28: note: candidates are:
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const v8::HandleScope&’
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note: v8::HandleScope::HandleScope()
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
../src/i2c.cc: At global scope:
../src/i2c.cc:77:17: error: ‘FunctionCallbackInfo’ does not name a type
../src/i2c.cc:77:17: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/i2c.cc:77:37: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/i2c.cc: In function ‘void Open(int)’:
../src/i2c.cc:79:28: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate*&)’
../src/i2c.cc:79:28: note: candidates are:
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const v8::HandleScope&’
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note: v8::HandleScope::HandleScope()
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
../src/i2c.cc:81:28: error: ‘args’ was not declared in this scope
../src/i2c.cc:83:62: error: no matching function for call to ‘v8::Local<v8::Value>::New(v8::Isolate*&, v8::Handle<v8::Primitive>)’
../src/i2c.cc:83:62: note: candidate is:
/usr/include/nodejs/deps/v8/include/v8.h:4197:10: note: static v8::Local<T> v8::Local<T>::New(v8::Handle<T>) [with T = v8::Value]
/usr/include/nodejs/deps/v8/include/v8.h:4197:10: note:   candidate expects 1 argument, 2 provided
../src/i2c.cc:87:28: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
../src/i2c.cc:95:29: error: ‘class v8::Isolate’ has no member named ‘GetCurrentContext’
../src/i2c.cc: At global scope:
../src/i2c.cc:99:17: error: ‘FunctionCallbackInfo’ does not name a type
../src/i2c.cc:99:17: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/i2c.cc:99:37: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/i2c.cc: In function ‘void Read(int)’:
../src/i2c.cc:101:28: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate*&)’
../src/i2c.cc:101:28: note: candidates are:
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const v8::HandleScope&’
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note: v8::HandleScope::HandleScope()
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
../src/i2c.cc:103:13: error: ‘args’ was not declared in this scope
../src/i2c.cc:105:41: error: invalid conversion from ‘v8::Isolate*’ to ‘int’ [-fpermissive]
/usr/include/nodejs/deps/v8/include/v8.h:1758:32: error:   initializing argument 1 of ‘static v8::Local<v8::Array> v8::Array::New(int)’ [-fpermissive]
../src/i2c.cc:108:62: error: no matching function for call to ‘v8::Local<v8::Value>::New(v8::Isolate*&, v8::Handle<v8::Primitive>)’
../src/i2c.cc:108:62: note: candidate is:
/usr/include/nodejs/deps/v8/include/v8.h:4197:10: note: static v8::Local<T> v8::Local<T>::New(v8::Handle<T>) [with T = v8::Value]
/usr/include/nodejs/deps/v8/include/v8.h:4197:10: note:   candidate expects 1 argument, 2 provided
../src/i2c.cc:111:28: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
../src/i2c.cc:114:48: error: invalid conversion from ‘v8::Isolate*’ to ‘int32_t {aka int}’ [-fpermissive]
/usr/include/nodejs/deps/v8/include/v8.h:1392:34: error:   initializing argument 1 of ‘static v8::Local<v8::Integer> v8::Integer::New(int32_t, v8::Isolate*)’ [-fpermissive]
../src/i2c.cc:114:48: error: invalid conversion from ‘char’ to ‘v8::Isolate*’ [-fpermissive]
/usr/include/nodejs/deps/v8/include/v8.h:1392:34: error:   initializing argument 2 of ‘static v8::Local<v8::Integer> v8::Integer::New(int32_t, v8::Isolate*)’ [-fpermissive]
../src/i2c.cc:124:29: error: ‘class v8::Isolate’ has no member named ‘GetCurrentContext’
../src/i2c.cc: At global scope:
../src/i2c.cc:128:21: error: ‘FunctionCallbackInfo’ does not name a type
../src/i2c.cc:128:21: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/i2c.cc:128:41: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/i2c.cc: In function ‘void ReadByte(int)’:
../src/i2c.cc:130:28: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate*&)’
../src/i2c.cc:130:28: note: candidates are:
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const v8::HandleScope&’
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note: v8::HandleScope::HandleScope()
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
../src/i2c.cc:133:62: error: no matching function for call to ‘v8::Local<v8::Value>::New(v8::Isolate*&, v8::Handle<v8::Primitive>)’
../src/i2c.cc:133:62: note: candidate is:
/usr/include/nodejs/deps/v8/include/v8.h:4197:10: note: static v8::Local<T> v8::Local<T>::New(v8::Handle<T>) [with T = v8::Value]
/usr/include/nodejs/deps/v8/include/v8.h:4197:10: note:   candidate expects 1 argument, 2 provided
../src/i2c.cc:138:28: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
../src/i2c.cc:140:37: error: invalid conversion from ‘v8::Isolate*’ to ‘int32_t {aka int}’ [-fpermissive]
/usr/include/nodejs/deps/v8/include/v8.h:1392:34: error:   initializing argument 1 of ‘static v8::Local<v8::Integer> v8::Integer::New(int32_t, v8::Isolate*)’ [-fpermissive]
../src/i2c.cc:140:37: error: invalid conversion from ‘int32_t {aka int}’ to ‘v8::Isolate*’ [-fpermissive]
/usr/include/nodejs/deps/v8/include/v8.h:1392:34: error:   initializing argument 2 of ‘static v8::Local<v8::Integer> v8::Integer::New(int32_t, v8::Isolate*)’ [-fpermissive]
../src/i2c.cc:143:7: error: ‘args’ was not declared in this scope
../src/i2c.cc:148:29: error: ‘class v8::Isolate’ has no member named ‘GetCurrentContext’
../src/i2c.cc:151:3: error: ‘args’ was not declared in this scope
../src/i2c.cc: At global scope:
../src/i2c.cc:154:22: error: ‘FunctionCallbackInfo’ does not name a type
../src/i2c.cc:154:22: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/i2c.cc:154:42: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/i2c.cc: In function ‘void ReadBlock(int)’:
../src/i2c.cc:156:28: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate*&)’
../src/i2c.cc:156:28: note: candidates are:
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const v8::HandleScope&’
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note: v8::HandleScope::HandleScope()
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
../src/i2c.cc:158:16: error: ‘args’ was not declared in this scope
../src/i2c.cc:161:62: error: no matching function for call to ‘v8::Local<v8::Value>::New(v8::Isolate*&, v8::Handle<v8::Primitive>)’
../src/i2c.cc:161:62: note: candidate is:
/usr/include/nodejs/deps/v8/include/v8.h:4197:10: note: static v8::Local<T> v8::Local<T>::New(v8::Handle<T>) [with T = v8::Value]
/usr/include/nodejs/deps/v8/include/v8.h:4197:10: note:   candidate expects 1 argument, 2 provided
../src/i2c.cc:166:30: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
../src/i2c.cc:175:31: error: ‘class v8::Isolate’ has no member named ‘GetCurrentContext’
../src/i2c.cc: At global scope:
../src/i2c.cc:189:18: error: ‘FunctionCallbackInfo’ does not name a type
../src/i2c.cc:189:18: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/i2c.cc:189:38: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/i2c.cc: In function ‘void Write(int)’:
../src/i2c.cc:191:28: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate*&)’
../src/i2c.cc:191:28: note: candidates are:
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const v8::HandleScope&’
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note: v8::HandleScope::HandleScope()
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
../src/i2c.cc:193:25: error: ‘args’ was not declared in this scope
../src/i2c.cc:198:62: error: no matching function for call to ‘v8::Local<v8::Value>::New(v8::Isolate*&, v8::Handle<v8::Primitive>)’
../src/i2c.cc:198:62: note: candidate is:
/usr/include/nodejs/deps/v8/include/v8.h:4197:10: note: static v8::Local<T> v8::Local<T>::New(v8::Handle<T>) [with T = v8::Value]
/usr/include/nodejs/deps/v8/include/v8.h:4197:10: note:   candidate expects 1 argument, 2 provided
../src/i2c.cc:201:28: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
../src/i2c.cc:209:29: error: ‘class v8::Isolate’ has no member named ‘GetCurrentContext’
../src/i2c.cc: At global scope:
../src/i2c.cc:213:22: error: ‘FunctionCallbackInfo’ does not name a type
../src/i2c.cc:213:22: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/i2c.cc:213:42: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/i2c.cc: In function ‘void WriteByte(int)’:
../src/i2c.cc:215:28: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate*&)’
../src/i2c.cc:215:28: note: candidates are:
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const v8::HandleScope&’
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note: v8::HandleScope::HandleScope()
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
../src/i2c.cc:217:17: error: ‘args’ was not declared in this scope
../src/i2c.cc:218:62: error: no matching function for call to ‘v8::Local<v8::Value>::New(v8::Isolate*&, v8::Handle<v8::Primitive>)’
../src/i2c.cc:218:62: note: candidate is:
/usr/include/nodejs/deps/v8/include/v8.h:4197:10: note: static v8::Local<T> v8::Local<T>::New(v8::Handle<T>) [with T = v8::Value]
/usr/include/nodejs/deps/v8/include/v8.h:4197:10: note:   candidate expects 1 argument, 2 provided
../src/i2c.cc:221:28: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
../src/i2c.cc:229:29: error: ‘class v8::Isolate’ has no member named ‘GetCurrentContext’
../src/i2c.cc: At global scope:
../src/i2c.cc:233:23: error: ‘FunctionCallbackInfo’ does not name a type
../src/i2c.cc:233:23: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/i2c.cc:233:43: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/i2c.cc: In function ‘void WriteBlock(int)’:
../src/i2c.cc:235:28: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate*&)’
../src/i2c.cc:235:28: note: candidates are:
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const v8::HandleScope&’
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note: v8::HandleScope::HandleScope()
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
../src/i2c.cc:237:25: error: ‘args’ was not declared in this scope
../src/i2c.cc:243:62: error: no matching function for call to ‘v8::Local<v8::Value>::New(v8::Isolate*&, v8::Handle<v8::Primitive>)’
../src/i2c.cc:243:62: note: candidate is:
/usr/include/nodejs/deps/v8/include/v8.h:4197:10: note: static v8::Local<T> v8::Local<T>::New(v8::Handle<T>) [with T = v8::Value]
/usr/include/nodejs/deps/v8/include/v8.h:4197:10: note:   candidate expects 1 argument, 2 provided
../src/i2c.cc:246:28: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
../src/i2c.cc:254:29: error: ‘class v8::Isolate’ has no member named ‘GetCurrentContext’
../src/i2c.cc: At global scope:
../src/i2c.cc:258:22: error: ‘FunctionCallbackInfo’ does not name a type
../src/i2c.cc:258:22: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/i2c.cc:258:42: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/i2c.cc: In function ‘void WriteWord(int)’:
../src/i2c.cc:260:28: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate*&)’
../src/i2c.cc:260:28: note: candidates are:
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const v8::HandleScope&’
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note: v8::HandleScope::HandleScope()
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
../src/i2c.cc:262:16: error: ‘args’ was not declared in this scope
../src/i2c.cc:265:62: error: no matching function for call to ‘v8::Local<v8::Value>::New(v8::Isolate*&, v8::Handle<v8::Primitive>)’
../src/i2c.cc:265:62: note: candidate is:
/usr/include/nodejs/deps/v8/include/v8.h:4197:10: note: static v8::Local<T> v8::Local<T>::New(v8::Handle<T>) [with T = v8::Value]
/usr/include/nodejs/deps/v8/include/v8.h:4197:10: note:   candidate expects 1 argument, 2 provided
../src/i2c.cc:268:28: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
../src/i2c.cc:276:29: error: ‘class v8::Isolate’ has no member named ‘GetCurrentContext’
../src/i2c.cc: In function ‘void Init(v8::Handle<v8::Object>)’:
../src/i2c.cc:281:52: error: no matching function for call to ‘SetMethod(v8::Handle<v8::Object>&, const char [11], void (&)(int))’
../src/i2c.cc:281:52: note: candidate is:
/usr/include/nodejs/src/node.h:112:6: note: template<class target_t> void node::SetMethod(target_t, const char*, v8::InvocationCallback)
../src/i2c.cc:282:40: error: no matching function for call to ‘SetMethod(v8::Handle<v8::Object>&, const char [5], void (&)(int))’
../src/i2c.cc:282:40: note: candidate is:
/usr/include/nodejs/src/node.h:112:6: note: template<class target_t> void node::SetMethod(target_t, const char*, v8::InvocationCallback)
../src/i2c.cc:283:40: error: no matching function for call to ‘SetMethod(v8::Handle<v8::Object>&, const char [5], void (&)(int))’
../src/i2c.cc:283:40: note: candidate is:
/usr/include/nodejs/src/node.h:112:6: note: template<class target_t> void node::SetMethod(target_t, const char*, v8::InvocationCallback)
../src/i2c.cc:284:42: error: no matching function for call to ‘SetMethod(v8::Handle<v8::Object>&, const char [6], void (&)(int))’
../src/i2c.cc:284:42: note: candidate is:
/usr/include/nodejs/src/node.h:112:6: note: template<class target_t> void node::SetMethod(target_t, const char*, v8::InvocationCallback)
../src/i2c.cc:285:42: error: no matching function for call to ‘SetMethod(v8::Handle<v8::Object>&, const char [6], void (&)(int))’
../src/i2c.cc:285:42: note: candidate is:
/usr/include/nodejs/src/node.h:112:6: note: template<class target_t> void node::SetMethod(target_t, const char*, v8::InvocationCallback)
../src/i2c.cc:286:50: error: no matching function for call to ‘SetMethod(v8::Handle<v8::Object>&, const char [10], void (&)(int))’
../src/i2c.cc:286:50: note: candidate is:
/usr/include/nodejs/src/node.h:112:6: note: template<class target_t> void node::SetMethod(target_t, const char*, v8::InvocationCallback)
../src/i2c.cc:287:52: error: no matching function for call to ‘SetMethod(v8::Handle<v8::Object>&, const char [11], void (&)(int))’
../src/i2c.cc:287:52: note: candidate is:
/usr/include/nodejs/src/node.h:112:6: note: template<class target_t> void node::SetMethod(target_t, const char*, v8::InvocationCallback)
../src/i2c.cc:288:40: error: no matching function for call to ‘SetMethod(v8::Handle<v8::Object>&, const char [5], void (&)(int))’
../src/i2c.cc:288:40: note: candidate is:
/usr/include/nodejs/src/node.h:112:6: note: template<class target_t> void node::SetMethod(target_t, const char*, v8::InvocationCallback)
../src/i2c.cc:289:48: error: no matching function for call to ‘SetMethod(v8::Handle<v8::Object>&, const char [9], void (&)(int))’
../src/i2c.cc:289:48: note: candidate is:
/usr/include/nodejs/src/node.h:112:6: note: template<class target_t> void node::SetMethod(target_t, const char*, v8::InvocationCallback)
../src/i2c.cc:290:50: error: no matching function for call to ‘SetMethod(v8::Handle<v8::Object>&, const char [10], void (&)(int))’
../src/i2c.cc:290:50: note: candidate is:
/usr/include/nodejs/src/node.h:112:6: note: template<class target_t> void node::SetMethod(target_t, const char*, v8::InvocationCallback)
In file included from /usr/include/nodejs/src/node.h:62:0,
                 from ../src/i2c.cc:1:
/usr/include/nodejs/deps/v8/include/v8.h: In constructor ‘v8::Local<T>::Local(S*) [with S = node::Buffer, T = v8::Object]’:
../src/i2c.cc:162:47:   instantiated from here
/usr/include/nodejs/deps/v8/include/v8.h:281:60: error: no matching function for call to ‘v8::Handle<v8::Object>::Handle(node::Buffer*&)’
/usr/include/nodejs/deps/v8/include/v8.h:281:60: note: candidates are:
/usr/include/nodejs/deps/v8/include/v8.h:196:29: note: template<class S> v8::Handle::Handle(v8::Handle<S>)
/usr/include/nodejs/deps/v8/include/v8.h:184:19: note: v8::Handle<T>::Handle(T*) [with T = v8::Object]
/usr/include/nodejs/deps/v8/include/v8.h:184:19: note:   no known conversion for argument 1 from ‘node::Buffer*’ to ‘v8::Object*’
/usr/include/nodejs/deps/v8/include/v8.h:179:10: note: v8::Handle<T>::Handle() [with T = v8::Object]
/usr/include/nodejs/deps/v8/include/v8.h:179:10: note:   candidate expects 0 arguments, 1 provided
/usr/include/nodejs/deps/v8/include/v8.h:174:26: note: v8::Handle<v8::Object>::Handle(const v8::Handle<v8::Object>&)
/usr/include/nodejs/deps/v8/include/v8.h:174:26: note:   no known conversion for argument 1 from ‘node::Buffer*’ to ‘const v8::Handle<v8::Object>&’
make: *** [Release/obj.target/i2c/src/i2c.o] Error 1
make: Leaving directory `/home/storm/node_modules/i2c/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.8.13-bone74
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/storm/node_modules/i2c
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! i2c@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the i2c@0.2.1 install script.
npm ERR! This is most likely a problem with the i2c package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls i2c
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.8.13-bone74
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "i2c"
npm ERR! cwd /home/storm
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/storm/npm-debug.log
npm ERR! not ok code 0

**Comment by kelly** [comment]
https://github.com/kelly/node-i2c#node-011-and-under

**Comment by stormbytes** [comment]
Thanks! 

My bad!
