### ISSUE TITLE
i2c module failed to install BeagleBoneBlack

### ISSUE THREAD

**Issue by pradhanshrijal** [kelly/node-i2c#68]
#npm install -g i2c

Error:

![i2c-err](https://cloud.githubusercontent.com/assets/11836341/9543219/4a75450c-4da1-11e5-8946-f1c91f848abe.JPG)

**Comment by pradhanshrijal** [comment]
It seems the common.gypi file is missing....and 
#npm rebuild
fails

**Comment by kelly** [comment]
something is wrong with your node-gyp. This isn't a problem with i2c.
